export const apiKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIzYzliMjIwYy02YzZkLTQ4NjktODAwNy02OTEyY2Q0YjBiNjEiLCJzdWIiOiJjNGZlZTI1NC1mYzMxLTRkMjMtYWFmNy1iZGJlOThiNDJmM2QiLCJpYXQiOjE3MzI3MjY4MTN9.WiGH-JyDGtTWXhapajeOq9gdFePVIXtBf0gt-ws40DI";
export const apiUrl = "https://api.gameshift.dev/nx/users";
