spring:
  application:
    name: BE_UDPM_9_UngDungChoThueNha
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://sql7.freesqldatabase.com/sql7744466}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:sql7744466}
    password: ${DATASOURCE_PASSWORD:ZVNbw1G59M}
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
